global:
  scrape_interval: 10s
  
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - prometheus:9090
       
 - job_name: cadvisor
   static_configs:
    - targets:
       - cadvisor:8080
       
 - job_name: threadservice
   static_configs:
    - targets:
       - threadservice:8081
       
 - job_name: postservice
   static_configs:
    - targets:
       - postservice:8081
 
 - job_name: commentservice
   static_configs:
    - targets:
       - commentservice:8081