@startuml Architecture_C3
title Forum application C3 model AccountService
' !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!include <C4/C4_Component>
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/dotnet.puml
!include DEVICONS/postgresql.puml
!include FONTAWESOME/users.puml

Container(api, "API gateway", "ASP.NET", "Handles client requests and manages the routing of requests to the microservices", $sprite="dotnet")

System_Boundary(ams,"AccountService"){
    Component(acontroller, "Account controller", "Controller")
    Component(alogic, "Account logic", "logic")
    Component(adal, "Account DAL", "DAL")
}
ContainerDb(userdb, "UserDB", "PostgreSQL", "User information and profiles", $sprite="postgresql")

System_Boundary(aams,"AuthService","Microservice"){
Component(aac, "Account creation", "Endpoint")
}

System_Boundary(mb, "Message Broker", " "){
Container(mq, "Kafka", "MessageBroker")
}

Rel(api, acontroller, "https")
Rel(api, aac, "https")

ams -[hidden]> aams

acontroller --> alogic
alogic --> adal

acontroller -[hidden]> aams

adal --> userdb

aac .. mq : messaging
mq .. acontroller : messaging

' Rel(aac, mq, "Messaging")
' Rel(mq, acontroller, "Messaging")

SHOW_LEGEND()
@enduml