@startuml SequenceDiagram_ViewPosts
title Forum application viewing posts sequence diagram
' !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include <C4/C4_Component>

' Containers
actor User as user
participant Gateway as api
participant ThreadService as threads
participant PostService as posts
participant CommentService as comments
queue Kafka as mq
database ThreadDB as tdb
database PostDB as pdb
database CommentDB as cdb

' Relations
autonumber
user -> api : Sends request
api -> posts : Routes request
autonumber stop
posts -> pdb : Reads/Writes
posts --> mq : Messaging

threads <-- mq : Messaging
threads -> tdb: Reads/Writes
threads --> mq : Messaging

comments <-- mq : Messaging
comments -> cdb: Reads/Writes
comments --> mq : Messaging

posts <-- mq : Messaging
autonumber 3
api <- posts : Processes request
user <- api : Sends response
autonumber stop


''authservice --> mq : Messaging
''mq --> accservice : Messaging
''accservice --> userdb : Reads/Writes

' SHOW_LEGEND()
@enduml