@startuml Walkthrough_ViewPosts
title Forum application walkthrough viewing posts
' !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!include <C4/C4_Component>
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/react.puml
!include DEVICONS/dotnet.puml
!include DEVICONS/postgresql.puml
!include FONTAWESOME/users.puml

' Containers
Person(user, "User", "User of the application", $sprite="users")

Container(frontend, "Frontend", "react", "Frontend user interface", $sprite="react")

Container(api, "API Gateway", "ASP.NET", "Handles client requests and manages the routing of requests to the microservices", $sprite="dotnet")

Container(threadservice, "ThreadService", "ASP.NET", "Threads", $sprite="dotnet")
Container(postservice, "PostService", "ASP.NET", "Posts", $sprite="dotnet")
Container(commentservice, "CommentService", "ASP.NET", "Comments", $sprite="dotnet")

ContainerDb(threaddb, "ThreadDB", "MongoDB", "Threads", $sprite="mongodb")
ContainerDb(postdb, "PostDB", "MongoDB", "Posts", $sprite="mongodb")
ContainerDb(commentdb, "CommentDB", "MongoDB", "Comments", $sprite="mongodb")

ComponentQueue(mq, "Kafka", "MessageBroker")

' Relations
user -> frontend : https
user <- frontend : https
frontend --> api : https
api --> postservice : https
api <-- postservice : https
frontend <-- api : https

''api -[hidden]-> mq
api -[hidden]-> threadservice
api -[hidden]-> postservice
api -[hidden]-> commentservice

threadservice -[hidden]> postservice
postservice -[hidden]> commentservice

threadservice .. mq : Messaging
postservice .. mq : Messaging
commentservice .. mq : Messaging
mq -[hidden]-> threaddb
mq -[hidden]-> postdb
mq -[hidden]-> commentdb

threadservice --> threaddb : Reads/Writes
postservice --> postdb : Reads/Writes
commentservice --> commentdb : Reads/Writes


''api -[hidden]-> mq
''api -[hidden]-> accservice

''authservice . mq : msg
''mq . accservice : msg

''authservice --> authdb : Reads/Writes
''accservice --> userdb : Reads/Writes

SHOW_LEGEND()
@enduml