@startuml SequenceDiagram_AccountCreation
title Forum application account creation sequence diagram
' !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include <C4/C4_Component>

' Containers
actor User as user
participant Gateway as api
participant AuthService as authservice
participant AccountService as accservice
queue Kafka as mq

' Relations
autonumber
user -> api : Sends request
activate api
api -> authservice : Routes request
activate authservice

api <- authservice : Processes request
deactivate authservice
user <- api : Sends response
deactivate api
autonumber stop

authservice --> mq : Messaging
mq --> accservice : Messaging

' SHOW_LEGEND()
@enduml